/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#005235',
        'primary-container': '#1a6b4a',
        'on-primary': '#ffffff',
        'on-primary-container': '#9be9bf',
        'primary-fixed': '#a5f3c9',
        'primary-fixed-dim': '#8ad6ae',
        'on-primary-fixed': '#002113',
        'on-primary-fixed-variant': '#005235',
        secondary: '#a33e00',
        'secondary-container': '#fd6c1a',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#581e00',
        'secondary-fixed': '#ffdbcd',
        'secondary-fixed-dim': '#ffb596',
        tertiary: '#003ea8',
        'tertiary-container': '#0053db',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#dbe1ff',
        'tertiary-fixed-dim': '#b4c5ff',
        'on-tertiary-fixed-variant': '#003ea8',
        surface: '#fbf9f5',
        'surface-dim': '#dbdad6',
        'surface-bright': '#fbf9f5',
        'surface-container': '#f0eeea',
        'surface-container-low': '#f5f3ef',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e4e2de',
        'surface-container-lowest': '#ffffff',
        'surface-tint': '#1a6b4a',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#3f4943',
        background: '#fbf9f5',
        'on-background': '#1b1c1a',
        outline: '#6f7a72',
        'outline-variant': '#bfc9c0',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f0ec',
        'inverse-primary': '#8ad6ae',
      },
      fontFamily: {
        sans: ['DM Sans', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
